apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0e4de12fcaa4ba36a
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-06b97084f4bb0b954
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
  volumeName: pv-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 
  volumeName: pv-wordpress
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - image: mysql:5.6
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345678"
        - name: MYSQL_DATABASE
          value: wpdb
        - name: MYSQL_USER
          value: wpuser
        - name: MYSQL_ROOT_HOST
          value: '%'  
        - name: MYSQL_PASSWORD
          value: "12345678"
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: db-contents
          mountPath: /var/lib/mysql
  volumes:
    - name: db-contents
      persistentVolumeClaim:
        claimName: pvc-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: mysql:3306
          - name: WORDPRESS_DB_NAME
            value: wpdb
          - name: WORDPRESS_DB_USER
            value: wpuser
          - name: WORDPRESS_DB_PASSWORD
            value: P@ssw0rd
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wp-contents
              mountPath: /var/www/html
      volumes:
        - name: wp-contents
          persistentVolumeClaim:
            claimName: pvc-wordpress
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress